<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-12">
<meta name="description" content="How SWE-bench Verified became the gold standard for measuring AI coding ability — and how the scores went from laughable to alarming in less than two years.">

<title>3&nbsp; The Benchmark Revolution – Something Big Already Happened</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/04-autonomous-frontier.html" rel="next">
<link href="../chapters/02-voices-of-warning.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dd7be1b65fbd8a0e56379a01f75a5202.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0cd002fe4c2a8524992fa81d2792e533.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3937d65ec731be4c3f5d1698a8cd2adb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-dark-7f112728eb3da13021bc0723d7d15c52.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles/theme.css">
<link rel="stylesheet" href="../styles/components.css">
<link rel="stylesheet" href="../styles/print.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/03-benchmark-revolution.html">Part II: The Evidence</a></li><li class="breadcrumb-item"><a href="../chapters/03-benchmark-revolution.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Benchmark Revolution</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Something Big Already Happened</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/zeroshotpress/Something-Big-Already-Happened" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/00-frontmatter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Front Matter</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: The Predictions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-the-prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Something Big Is Happening</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-voices-of-warning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Chorus of Warnings</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: The Evidence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-benchmark-revolution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Benchmark Revolution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-autonomous-frontier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">The Autonomous Frontier</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-model-avalanche.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Model Avalanche</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-human-cost.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Human Cost</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: The Inflection</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-recursive-loop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Recursive Loop</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-november-revolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The November Revolution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-software-factory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Software Factory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-compounding-teams.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The Compounding Teams</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV: The Broader Impact</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-investment-tsunami.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">The Investment Tsunami</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-geopolitical-chessboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">The Geopolitical Chessboard</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V: What Comes Next</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-science-acceleration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Science Acceleration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-what-now.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">What Now?</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-swe-bench-actually-measures" id="toc-what-swe-bench-actually-measures" class="nav-link active" data-scroll-target="#what-swe-bench-actually-measures"><span class="header-section-number">3.1</span> What SWE-bench Actually Measures</a></li>
  <li><a href="#the-progression-from-2.7-to-79.2" id="toc-the-progression-from-2.7-to-79.2" class="nav-link" data-scroll-target="#the-progression-from-2.7-to-79.2"><span class="header-section-number">3.2</span> The Progression: From 2.7% to 79.2%</a>
  <ul class="collapse">
  <li><a href="#the-early-phase-proof-of-concept-janjun-2024" id="toc-the-early-phase-proof-of-concept-janjun-2024" class="nav-link" data-scroll-target="#the-early-phase-proof-of-concept-janjun-2024"><span class="header-section-number">3.2.1</span> The Early Phase: Proof of Concept (Jan–Jun 2024)</a></li>
  <li><a href="#the-breakthrough-phase-reasoning-models-sep-2024feb-2025" id="toc-the-breakthrough-phase-reasoning-models-sep-2024feb-2025" class="nav-link" data-scroll-target="#the-breakthrough-phase-reasoning-models-sep-2024feb-2025"><span class="header-section-number">3.2.2</span> The Breakthrough Phase: Reasoning Models (Sep 2024–Feb 2025)</a></li>
  <li><a href="#the-maturity-phase-converging-at-the-top-mar-2025feb-2026" id="toc-the-maturity-phase-converging-at-the-top-mar-2025feb-2026" class="nav-link" data-scroll-target="#the-maturity-phase-converging-at-the-top-mar-2025feb-2026"><span class="header-section-number">3.2.3</span> The Maturity Phase: Converging at the Top (Mar 2025–Feb 2026)</a></li>
  <li><a href="#sec-november-cluster" id="toc-sec-november-cluster" class="nav-link" data-scroll-target="#sec-november-cluster"><span class="header-section-number">3.2.4</span> The November 2025 Cluster: The Inflection Point</a></li>
  </ul></li>
  <li><a href="#what-79-means-for-software-engineering" id="toc-what-79-means-for-software-engineering" class="nav-link" data-scroll-target="#what-79-means-for-software-engineering"><span class="header-section-number">3.3</span> What 79% Means for Software Engineering</a></li>
  <li><a href="#sec-29-percent" id="toc-sec-29-percent" class="nav-link" data-scroll-target="#sec-29-percent"><span class="header-section-number">3.4</span> The 29% Finding</a></li>
  <li><a href="#sec-experience-gap" id="toc-sec-experience-gap" class="nav-link" data-scroll-target="#sec-experience-gap"><span class="header-section-number">3.5</span> The Experience Gap</a></li>
  <li><a href="#the-acceleration-pattern" id="toc-the-acceleration-pattern" class="nav-link" data-scroll-target="#the-acceleration-pattern"><span class="header-section-number">3.6</span> The Acceleration Pattern</a></li>
  <li><a href="#the-competition-factor" id="toc-the-competition-factor" class="nav-link" data-scroll-target="#the-competition-factor"><span class="header-section-number">3.7</span> The Competition Factor</a></li>
  <li><a href="#sec-beyond-swebench" id="toc-sec-beyond-swebench" class="nav-link" data-scroll-target="#sec-beyond-swebench"><span class="header-section-number">3.8</span> Beyond SWE-bench</a></li>
  <li><a href="#the-benchmarks-blind-spots" id="toc-the-benchmarks-blind-spots" class="nav-link" data-scroll-target="#the-benchmarks-blind-spots"><span class="header-section-number">3.9</span> The Benchmark’s Blind Spots</a></li>
  <li><a href="#what-79.2-means-for-ten-engineers" id="toc-what-79.2-means-for-ten-engineers" class="nav-link" data-scroll-target="#what-79.2-means-for-ten-engineers"><span class="header-section-number">3.10</span> What 79.2% Means for Ten Engineers</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/zeroshotpress/Something-Big-Already-Happened/edit/main/chapters/03-benchmark-revolution.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/zeroshotpress/Something-Big-Already-Happened/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/03-benchmark-revolution.html">Part II: The Evidence</a></li><li class="breadcrumb-item"><a href="../chapters/03-benchmark-revolution.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Benchmark Revolution</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-benchmark-revolution" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Benchmark Revolution</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>In the fall of 2023, Carlos Jiménez sat at a workstation in Princeton, New Jersey, watching another language model fail. Output scrolled across his terminal — wrong file, wrong function, patch rejected by the test suite. The PhD candidate had grown up in Salt Lake City, studied computer science at the University of Utah, then headed east to work with professor Karthik Narasimhan on a problem that sounded simple and turned out to be brutally hard: could a language model fix real software bugs?</p>
<!-- PROOF: url=https://www.carlosejimenez.com/ | accessed=2026-02-14 | key=jimenez_bio -->
<!-- PROOF: url=https://arxiv.org/abs/2310.06770 | accessed=2026-02-14 | key=jimenez2024_swebench -->
<p>It was a moment of peak AI hype. ChatGPT had launched the previous November and reached a hundred million users in two months. Every tech company was bolting AI features onto its products. But Jiménez wasn’t building chatbots. He wanted to know something specific: could these systems do the <em>work</em> — the tedious, detail-oriented, test-it-till-it-passes work — of professional software engineering?</p>
<p>He’d spent months building the answer machine. SWE-bench: 2,294 tasks scraped from twelve production Python repositories — Django, Flask, scikit-learn, sympy, and others. Each task was a real bug report filed by a real developer, paired with the full codebase and a test suite that would judge whether the fix worked. No toy problems. No LeetCode puzzles. The actual daily grind of software maintenance.</p>
<p>The protocol was merciless. Give the model the bug report. Give it the codebase. No hints about which file to edit, no guidance on approach. Just: here’s the problem, here’s the code, fix it.</p>
<p>GPT-4 — the most capable model available — resolved 2.7% of the tasks. One in thirty-seven. Jiménez had designed the benchmark to be hard. He hadn’t expected it to be <em>this</em> hard.</p>
<p>He submitted the paper to ICLR, where it was accepted for the 2024 conference. He couldn’t have known that within two years, every major AI lab on the planet would be racing to top his leaderboard — that the score would climb from that initial 2.7% to 79.2% — that the measuring stick he’d built at Princeton would become the most-cited number in arguments about whether artificial intelligence was coming for the software engineering profession.</p>
<p>The voices of warning documented in the previous chapter made bold claims. But predictions are cheap. Evidence is what matters. And in the field of AI-assisted software engineering, Jiménez’s benchmark became the definitive measure of whether those predictions were coming true.</p>
<section id="what-swe-bench-actually-measures" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="what-swe-bench-actually-measures"><span class="header-section-number">3.1</span> What SWE-bench Actually Measures</h2>
<p>SWE-bench is not an artificial test. It does not ask models to solve textbook exercises or complete coding puzzles. Instead, it draws from real issues filed against real open-source repositories — projects like Django, Flask, scikit-learn, and sympy. Each task consists of a bug report or feature request, the corresponding codebase, and the test suite that defines whether the fix is correct <span class="citation" data-cites="epoch2025_swebench">(<a href="#ref-epoch2025_swebench" role="doc-biblioref">Epoch AI 2025</a>)</span>.</p>
<p>To solve a SWE-bench task, an AI system must:</p>
<ol type="1">
<li>Read and understand the issue description</li>
<li>Explore a large, unfamiliar codebase</li>
<li>Identify the relevant files and functions</li>
<li>Write a correct patch that resolves the issue</li>
<li>Pass the existing test suite without breaking anything</li>
</ol>
<p>The tasks demand the daily work of professional software engineers — reading comprehension, code navigation, debugging intuition, and the ability to reason about complex system interactions.</p>
<p>In August 2024, OpenAI and the benchmark authors introduced SWE-bench Verified, a human-audited subset of 500 tasks designed to eliminate ambiguous or poorly specified issues <span class="citation" data-cites="openai2024_swebenchverified">(<a href="#ref-openai2024_swebenchverified" role="doc-biblioref">OpenAI 2024</a>)</span>. This version became the standard against which all subsequent models have been measured.</p>
<p>The need for a verified subset was itself revealing. The original SWE-bench dataset contained tasks where the “correct” solution was disputed, where the test suite was incomplete, or where the issue description was too vague for even a skilled human to resolve reliably. By hand-auditing 500 tasks, the benchmark authors created a cleaner signal — one that separated genuine AI capability from noise. The trade-off was a smaller dataset, but the gains in measurement reliability were substantial. After August 2024, virtually every major lab reported results on Verified rather than the original benchmark, making it the de facto standard for the field.</p>
</section>
<section id="the-progression-from-2.7-to-79.2" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="the-progression-from-2.7-to-79.2"><span class="header-section-number">3.2</span> The Progression: From 2.7% to 79.2%</h2>
<p>The trajectory of SWE-bench scores reads like an exponential curve. <a href="#fig-swe-bench-timeline" class="quarto-xref">Figure&nbsp;<span class="quarto-unresolved-ref">fig-swe-bench-timeline</span></a> shows the progression from early 2024 through February 2026.</p>
<div id="fig-swe-bench-timeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-swe-bench-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../images/generated/swe-bench-timeline.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-swe-bench-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: SWE-bench Verified progression: AI coding performance from January 2024 through February 2026.
</figcaption>
</figure>
</div>
<p>The key milestones, summarized in <a href="#tbl-swebench-scores" class="quarto-xref">Table&nbsp;<span class="quarto-unresolved-ref">tbl-swebench-scores</span></a>, tell their own story:</p>
<div id="tbl-swebench-scores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-swebench-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: Top SWE-bench Verified scores by date, showing the progression from single-digit to near-80% performance.
</figcaption>
<div aria-describedby="tbl-swebench-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Date</th>
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Score</th>
<th style="text-align: left;">Organization</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jan 2024</td>
<td style="text-align: left;">GPT-4 (RAG baseline)</td>
<td style="text-align: right;">2.7%</td>
<td style="text-align: left;">OpenAI</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mar 2024</td>
<td style="text-align: left;">Devin</td>
<td style="text-align: right;">13.86%</td>
<td style="text-align: left;">Cognition</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Apr 2024</td>
<td style="text-align: left;">AutoCodeRover</td>
<td style="text-align: right;">22.0%</td>
<td style="text-align: left;">NUS/Industry</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jun 2024</td>
<td style="text-align: left;">MentatBot + GPT-4o</td>
<td style="text-align: right;">38.0%</td>
<td style="text-align: left;">AbanteAI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jul 2024</td>
<td style="text-align: left;">CodeStory Aide</td>
<td style="text-align: right;">43.0%</td>
<td style="text-align: left;">CodeStory</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aug 2024</td>
<td style="text-align: left;">GPT-4o (Verified baseline)</td>
<td style="text-align: right;">33.0%</td>
<td style="text-align: left;">OpenAI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sep 2024</td>
<td style="text-align: left;">o1-preview</td>
<td style="text-align: right;">45.0%</td>
<td style="text-align: left;">OpenAI</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oct 2024</td>
<td style="text-align: left;">Claude 3.5 Sonnet</td>
<td style="text-align: right;">49.0%</td>
<td style="text-align: left;">Anthropic</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dec 2024</td>
<td style="text-align: left;">o3</td>
<td style="text-align: right;">72.0%</td>
<td style="text-align: left;">OpenAI</td>
</tr>
<tr class="even">
<td style="text-align: left;">Feb 2025</td>
<td style="text-align: left;">Claude 3.7 Sonnet</td>
<td style="text-align: right;">55.0%</td>
<td style="text-align: left;">Anthropic</td>
</tr>
<tr class="odd">
<td style="text-align: left;">May 2025</td>
<td style="text-align: left;">Claude Sonnet 4</td>
<td style="text-align: right;">62.0%</td>
<td style="text-align: left;">Anthropic</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jun 2025</td>
<td style="text-align: left;">TRAE (multi-model)</td>
<td style="text-align: right;">75.2%</td>
<td style="text-align: left;">ByteDance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aug 2025</td>
<td style="text-align: left;">GPT-5</td>
<td style="text-align: right;">74.9%</td>
<td style="text-align: left;">OpenAI</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nov 2025</td>
<td style="text-align: left;">Gemini 3 Pro + agent</td>
<td style="text-align: right;">77.4%</td>
<td style="text-align: left;">Google DeepMind</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nov 2025</td>
<td style="text-align: left;">Claude Opus 4.5 + agent</td>
<td style="text-align: right;">79.2%</td>
<td style="text-align: left;">Anthropic</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dec 2025</td>
<td style="text-align: left;">GPT-5.2</td>
<td style="text-align: right;">75.4%</td>
<td style="text-align: left;">OpenAI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Feb 2026</td>
<td style="text-align: left;">Claude Opus 4.6 (Thinking)</td>
<td style="text-align: right;">79.2%</td>
<td style="text-align: left;">Anthropic</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Several patterns emerge from this data.</p>
<section id="the-early-phase-proof-of-concept-janjun-2024" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="the-early-phase-proof-of-concept-janjun-2024"><span class="header-section-number">3.2.1</span> The Early Phase: Proof of Concept (Jan–Jun 2024)</h3>
<p>When GPT-4 scored 2.7% with a simple retrieval-augmented generation approach in January 2024, many researchers viewed AI-assisted software engineering as an interesting but impractical research direction. The score meant the model could solve roughly one in forty real-world bugs — not a useful tool for any professional.</p>
<p>Devin’s March 2024 announcement at 13.86% was significant not for its absolute score but for what it represented. Cognition Labs marketed Devin as “the first AI software engineer,” and while the marketing outpaced the reality, the five-fold improvement over the RAG baseline in just two months signaled that the problem was tractable <span class="citation" data-cites="cognition2024_devin">(<a href="#ref-cognition2024_devin" role="doc-biblioref">Cognition Labs 2024</a>)</span>.</p>
<p>By mid-2024, multi-model approaches combining Claude 3.5 Sonnet and GPT-4o were pushing past 40%. The benchmark was no longer a curiosity. It was a competitive arena.</p>
</section>
<section id="the-breakthrough-phase-reasoning-models-sep-2024feb-2025" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="the-breakthrough-phase-reasoning-models-sep-2024feb-2025"><span class="header-section-number">3.2.2</span> The Breakthrough Phase: Reasoning Models (Sep 2024–Feb 2025)</h3>
<p>The introduction of reasoning models — OpenAI’s o1 in September 2024 and o3 in December 2024 — represented a qualitative shift. These models did not simply generate code faster; they thought about problems differently, using chain-of-thought reasoning to plan their approach before writing a single line.</p>
<p>o1-preview scored 45%, respectable but not groundbreaking. o3, released in December 2024, scored 72% — a 27-percentage-point jump in three months <span class="citation" data-cites="openai2023_gpt4">(<a href="#ref-openai2023_gpt4" role="doc-biblioref">OpenAI 2023</a>)</span>. This single leap was larger than the entire improvement from January through September 2024.</p>
<p>Meanwhile, Anthropic’s Claude 3.5 Sonnet had reached 49% in October, and Claude 3.7 Sonnet would reach 55% by February 2025 — steady, substantial gains from a different architectural approach <span class="citation" data-cites="anthropic2024_swebench">(<a href="#ref-anthropic2024_swebench" role="doc-biblioref">Anthropic 2024</a>)</span>.</p>
</section>
<section id="the-maturity-phase-converging-at-the-top-mar-2025feb-2026" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="the-maturity-phase-converging-at-the-top-mar-2025feb-2026"><span class="header-section-number">3.2.3</span> The Maturity Phase: Converging at the Top (Mar 2025–Feb 2026)</h3>
<p>By mid-2025, the leading models were converging. Claude Sonnet 4 hit 62%. ByteDance’s TRAE reached 75.2% using a multi-model approach. GPT-5 landed at 74.9%. The differences between top models were narrowing even as absolute performance climbed.</p>
</section>
<section id="sec-november-cluster" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="sec-november-cluster"><span class="header-section-number">3.2.4</span> The November 2025 Cluster: The Inflection Point</h3>
<p>November 2025 stands as the most consequential month in the history of AI coding benchmarks. Within a span of six days, two models shattered what had seemed like a ceiling, and in doing so redefined the practical meaning of artificial intelligence for the software engineering profession.</p>
<p>On November 18, Google DeepMind released Gemini 3 Pro, which scored 77.4% on SWE-bench Verified when paired with an agentic scaffolding <span class="citation" data-cites="epoch2025_swebench google2025_gemini3">(<a href="#ref-epoch2025_swebench" role="doc-biblioref">Epoch AI 2025</a>; <a href="#ref-google2025_gemini3" role="doc-biblioref">Google DeepMind 2025</a>)</span>. The score represented a 2.5-percentage-point improvement over GPT-5’s August 2025 result of 74.9% — a modest gain in absolute terms, but one that carried it past the 75% threshold. At 77.4%, the model was resolving more than three out of every four verified software engineering tasks. For the first time, the balance had tipped: there were more tasks the AI could solve than tasks it could not.</p>
<p>Six days later, on November 24, Anthropic released Claude Opus 4.5. Its SWE-bench Verified score of 79.2% did not merely exceed Gemini 3 Pro’s result. It established a new ceiling that has yet to be surpassed as of this writing <span class="citation" data-cites="epoch2025_swebench">(<a href="#ref-epoch2025_swebench" role="doc-biblioref">Epoch AI 2025</a>)</span>. The 1.8-percentage-point gap between Gemini 3 Pro and Opus 4.5 may appear narrow, but at the top of a saturating benchmark, each additional point represents the resolution of progressively harder problems — the ambiguous bug reports, the deeply nested codebases, the issues that require not just technical skill but something approaching engineering judgment.</p>
<p>What made the November cluster significant was the concentration. Two models from two competing organizations, released within a week of each other, both pushing past 77%. Because the underlying capabilities — chain-of-thought reasoning, tool use during problem-solving, sustained error recovery — had matured independently, near-80% performance was now reproducible across different architectures and different training approaches. Convergence, not coincidence.</p>
<p>The scores also need to be understood in the context of the broader November model release wave discussed in <a href="#sec-november-precedent" class="quarto-xref"><span class="quarto-unresolved-ref">sec-november-precedent</span></a>. Grok 4.1 had arrived on November 17, pushing LMArena Elo to 1,483. Gemini 3 topped that the next day at 1,501 Elo. Opus 4.5 arrived six days later with the SWE-bench crown. And within three weeks, GPT-5.2 and Gemini 3 Deep Think would further extend the frontier of reasoning capability. The competitive pressure was intense and mutually reinforcing. Each release gave the other labs’ customers a reason to demand better tools, and each lab had models ready or nearly ready that could deliver.</p>
<p>By February 2026, when Claude Opus 4.6 matched the 79.2% with its thinking capabilities, the benchmark had arguably reached a saturation point. The remaining 20% of unsolved tasks likely represented genuinely ambiguous issues, tasks requiring deep domain knowledge, or problems that were poorly specified in the original repositories. AI competence on standard software engineering tasks was settled. What remained was the meaning of the ceiling — whether the last 20% represented a fundamental limit or merely the next target.</p>
</section>
</section>
<section id="what-79-means-for-software-engineering" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="what-79-means-for-software-engineering"><span class="header-section-number">3.3</span> What 79% Means for Software Engineering</h2>
<p>Sundar Pichai had called it “the most profound technology humanity is ever working on” <span class="citation" data-cites="pichai2025_bbc">(<a href="#ref-pichai2025_bbc" role="doc-biblioref">Pichai 2025</a>)</span>. A score of 79.2% on SWE-bench Verified gave that claim specific, concrete implications for the software engineering profession. <!-- PROOF: url=https://fortune.com/2025/12/02/ai-wipes-jobs-google-ceo-sundar-pichai-everyday-people-to-adapt-accordingly/ | accessed=2026-02-14 | key=pichai2025_bbc --></p>
<p>It means that when presented with a random bug report from a production open-source codebase, an AI system can trace through the code, identify the problem, and write a correct fix roughly four times out of five. It can do this in minutes rather than the hours or days a human engineer might require. It can do it at any time of day, without needing to ramp up on the codebase, and without introducing the human errors that come from fatigue or distraction.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What 79% Does Not Mean
</div>
</div>
<div class="callout-body-container callout-body">
<p>A 79.2% SWE-bench score does not mean AI can replace 79.2% of software engineers. Software engineering encompasses far more than resolving bug reports: architecture design, requirements gathering, code review, system operations, stakeholder communication, and judgment calls about trade-offs. SWE-bench measures one important dimension of the job, but not the whole job.</p>
<p>That said, resolving issues against existing codebases is a significant fraction of what junior and mid-level engineers spend their time on. The implications for entry-level software engineering roles are real and immediate.</p>
</div>
</div>
<p>The implications for hiring are already visible. By late 2025, multiple technology companies had begun restructuring their engineering organizations, reducing headcount at the junior level while increasing investment in senior engineers who could supervise and direct AI systems <span class="citation" data-cites="cnbc2025_layoffs">(<a href="#ref-cnbc2025_layoffs" role="doc-biblioref">CNBC 2025</a>)</span>. The traditional career pipeline — where graduates enter as junior engineers, fix bugs, write tests, and gradually take on more complex work — is being compressed. If an AI can handle the bug-fixing and test-writing that once served as the training ground for new engineers, then the on-ramp to the profession narrows. Companies that once posted dozens of entry-level software engineering positions began, by early 2026, posting fewer such roles and instead seeking candidates with the ability to architect systems, review AI-generated code, and specify complex requirements clearly <span class="citation" data-cites="hbr2026_aijobs">(<a href="#ref-hbr2026_aijobs" role="doc-biblioref">Harvard Business Review 2026</a>)</span>.</p>
<p>The economic implications extend beyond hiring. If an AI system can resolve most routine software engineering tasks, then organizations need fewer humans for those tasks. This does not necessarily mean fewer software engineers in total — demand for software is effectively infinite, and AI may enable small teams to tackle projects that previously required large ones. But it does mean that the nature of the work is changing, and that the skills that defined a good junior engineer in 2023 are not the same skills that will define one in 2027.</p>
</section>
<section id="sec-29-percent" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-29-percent"><span class="header-section-number">3.4</span> The 29% Finding</h2>
<p>SWE-bench measures what AI can do in a controlled evaluation setting. But how much code is AI actually writing in the real world? On January 22, 2026, a study published in <em>Science</em> — one of the most prestigious peer-reviewed journals in the world — provided the first rigorous answer. The number was startling: 29% of Python functions committed to GitHub by U.S.-based developers were AI-generated <span class="citation" data-cites="daniotti2026_aicoding">(<a href="#ref-daniotti2026_aicoding" role="doc-biblioref">Daniotti et al. 2026</a>)</span>.</p>
<p>The study, led by Simone Daniotti at the Complexity Science Hub and Utrecht University, was notable for the rigor of its methodology. Rather than relying on self-reported surveys — which are prone to social desirability bias and imprecise definitions of what counts as “AI-generated” — the team trained a neural classifier to detect AI-generated Python functions directly from code. They applied this classifier to more than 30 million GitHub commits from approximately 160,000 developers, creating what was by far the largest empirical study of AI code adoption ever conducted <span class="citation" data-cites="daniotti2026_aicoding">(<a href="#ref-daniotti2026_aicoding" role="doc-biblioref">Daniotti et al. 2026</a>)</span>.</p>
<p>The 29% figure represented a dramatic acceleration. The study tracked adoption over time and found that the share of AI-generated Python functions among U.S. developers had risen from approximately 5% in 2022 to 29% by late 2024 and early 2025 — a nearly sixfold increase in roughly two years. Given the rate of capability improvement documented elsewhere in this chapter, the figure was almost certainly higher by the time the study was published in January 2026.</p>
<p>International comparisons revealed significant geographic variation. France stood at 24%, Germany at 23%, India at 20%, Russia at 15%, and China at 12% <span class="citation" data-cites="daniotti2026_aicoding">(<a href="#ref-daniotti2026_aicoding" role="doc-biblioref">Daniotti et al. 2026</a>)</span>. The U.S. led by a substantial margin, reflecting earlier access to frontier AI coding tools, higher adoption of tools like GitHub Copilot and Claude Code, and a developer culture that was more receptive to AI-assisted workflows. The gap between the U.S. and China was particularly striking — a factor of nearly 2.5 — and raised questions about whether AI coding adoption would become a source of competitive advantage between technology ecosystems.</p>
<p>The economic impact was substantial. The study estimated that AI-generated code contributed $23 to $38 billion in annual economic value to U.S. programming tasks, calculated from the overall 3.6% increase in quarterly output (measured in online code contributions) observed across their sample <span class="citation" data-cites="daniotti2026_aicoding">(<a href="#ref-daniotti2026_aicoding" role="doc-biblioref">Daniotti et al. 2026</a>)</span>. This figure was conservative by design, capturing only the directly measurable productivity effect and excluding harder-to-quantify benefits like reduced time-to-market, lower defect rates, or the enablement of projects that would not have been attempted without AI assistance.</p>
</section>
<section id="sec-experience-gap" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-experience-gap"><span class="header-section-number">3.5</span> The Experience Gap</h2>
<p>The <em>Science</em> study’s most consequential finding went beyond adoption rates or economic value. It revealed who benefited from AI coding tools — and who didn’t.</p>
<p>Less experienced programmers used AI in 37% of their code — a higher adoption rate than any other group. They were the most enthusiastic adopters, the most willing to delegate to AI tools, and the most likely to incorporate AI-generated functions into their commits. But their productivity gains were statistically indistinguishable from zero <span class="citation" data-cites="daniotti2026_aicoding">(<a href="#ref-daniotti2026_aicoding" role="doc-biblioref">Daniotti et al. 2026</a>)</span>.</p>
<p>Experienced developers, by contrast, used AI in 27% of their code — a lower adoption rate — but saw a 6.2% increase in commit rates at that level of adoption. The gap mattered. Six percent was the difference between a tool that made you more productive and one that merely rearranged how you spent your time <span class="citation" data-cites="daniotti2026_aicoding">(<a href="#ref-daniotti2026_aicoding" role="doc-biblioref">Daniotti et al. 2026</a>)</span>.</p>
<p>The finding was deeply counterintuitive and deeply consequential. The conventional wisdom about AI coding tools was that they would be the great equalizer — that by automating the routine aspects of programming, they would allow less experienced developers to punch above their weight, closing the gap between junior and senior engineers. The <em>Science</em> study found the opposite. The technology widens rather than narrows skill-based disparities in the profession.</p>
<p>The likely explanation involves the difference between generating code and evaluating code. AI coding tools excel at producing syntactically correct, functionally plausible code from a natural-language prompt. But knowing whether that code is correct — whether it handles edge cases, whether it introduces security vulnerabilities, whether it integrates properly with the broader system, whether it makes the right architectural trade-offs — requires exactly the kind of deep experience that junior developers lack. An experienced developer can review AI-generated code and quickly spot the subtle errors: the race condition, the missing null check, the inefficient database query that will scale poorly. A less experienced developer may accept the code at face value, spending their time generating more AI-written functions rather than ensuring the quality of each one.</p>
<p>This finding reframes the debate about AI’s impact on the software engineering labor market. If AI tools primarily benefit experienced developers — making the already-productive more productive while leaving the less-experienced treading water — then the implications for career development are troubling. The traditional apprenticeship model, where junior developers build expertise by writing code, making mistakes, and learning from the correction process, may be disrupted by a technology that allows juniors to bypass the learning phase entirely. They write less code, review less code, and debug less code — the very activities through which expertise is built.</p>
<p>The parallel to other domains is instructive. When calculators became ubiquitous in mathematics education, teachers debated whether students still needed to learn long division. The consensus, eventually, was that understanding the underlying process mattered even if the tool could do it faster. Programming may face an analogous question: does it matter that a developer understands how to write a function if the AI writes it better? The <em>Science</em> study suggests the answer is yes — because the developers who understand the underlying process are the ones who benefit from the tool, while those who do not understand it gain nothing.</p>
</section>
<section id="the-acceleration-pattern" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="the-acceleration-pattern"><span class="header-section-number">3.6</span> The Acceleration Pattern</h2>
<p>Perhaps the most important feature of the SWE-bench trajectory is not the absolute numbers but the rate of change. Consider the time required to achieve successive milestones:</p>
<ul>
<li><strong>2.7% to 13.9%</strong>: ~2 months (January to March 2024)</li>
<li><strong>13.9% to 49%</strong>: ~7 months (March to October 2024)</li>
<li><strong>49% to 72%</strong>: ~2 months (October to December 2024)</li>
<li><strong>72% to 79.2%</strong>: ~11 months (December 2024 to November 2025)</li>
</ul>
<p>The pattern shows a rapid acceleration through mid-range scores, followed by a slowdown as performance approaches the ceiling. This is characteristic of benchmark saturation: the easiest tasks are solved first, and each additional percentage point requires solving harder problems.</p>
<p>But this interpretation cuts both ways. The slowdown at the top may reflect genuine difficulty, or it may reflect the fact that 2025 saw fewer paradigm-shifting architectural innovations than 2024. The introduction of agent frameworks, extended thinking, and tool use during reasoning — all of which appeared in 2025 — may produce another acceleration phase.</p>
</section>
<section id="the-competition-factor" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="the-competition-factor"><span class="header-section-number">3.7</span> The Competition Factor</h2>
<p>One underappreciated driver of SWE-bench improvement is competition. By mid-2025, at least four major organizations were directly competing for the top score: Anthropic (Claude), OpenAI (GPT/o-series), Google DeepMind (Gemini), and a growing field of smaller players using multi-model approaches.</p>
<p>This competition created a flywheel. Each new high score generated headlines, attracted talent, and justified further investment. Anthropic’s Claude 3.5 Sonnet hitting 49% in October 2024 prompted OpenAI to push o3 to 72% just two months later. That result, in turn, drove Anthropic to invest heavily in the agentic capabilities that would eventually produce the 79.2% score.</p>
<p>The presence of open-source competitors added another dimension entirely. In January 2025, DeepSeek released R1, an open-source reasoning model under an MIT license that scored 45% on SWE-bench Verified — matching o1-preview’s September 2024 result <span class="citation" data-cites="deepseek2025_r1">(<a href="#ref-deepseek2025_r1" role="doc-biblioref">DeepSeek-AI 2025</a>)</span>. DeepSeek-R1 was built atop the DeepSeek-V3 architecture, a 671-billion-parameter mixture-of-experts model that had been trained for a reported $6 million — a fraction of the hundreds of millions that frontier labs were spending on comparable training runs <span class="citation" data-cites="deepseek2024_v3">(<a href="#ref-deepseek2024_v3" role="doc-biblioref">DeepSeek-AI 2024</a>)</span>. The consequences hit immediately. If an open-source model, trainable by a modestly funded Chinese lab, could match scores that OpenAI’s proprietary reasoning system had achieved just four months earlier, then the competitive moat around frontier AI capabilities was thinner than anyone had assumed. The release sent shockwaves through the industry, contributing to an 18% single-day drop in NVIDIA’s stock price and briefly making the DeepSeek chatbot the number-one app on Apple’s iOS store <span class="citation" data-cites="deepseek2025_r1">(<a href="#ref-deepseek2025_r1" role="doc-biblioref">DeepSeek-AI 2025</a>)</span>. For SWE-bench specifically, the message was clear: the benchmark’s middle range was no longer the exclusive domain of billion-dollar research budgets.</p>
</section>
<section id="sec-beyond-swebench" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="sec-beyond-swebench"><span class="header-section-number">3.8</span> Beyond SWE-bench</h2>
<p>SWE-bench Verified is the most prominent coding benchmark, but it is not the only one, and the proliferation of alternative benchmarks tells its own story about the field’s maturation.</p>
<p>SWE-Bench Pro emerged as a response to the saturation problem. As top models converged near 80% on SWE-bench Verified, the benchmark’s ability to discriminate between frontier systems diminished. SWE-Bench Pro addressed this by selecting harder tasks — issues that required deeper domain understanding, more complex multi-file modifications, and more sophisticated testing strategies. When GPT-5.3-Codex was released on February 5, 2026, OpenAI highlighted its new record on SWE-Bench Pro as evidence that the model’s capabilities extended beyond the original benchmark’s ceiling <span class="citation" data-cites="openai2026_codex">(<a href="#ref-openai2026_codex" role="doc-biblioref">OpenAI 2026</a>)</span>. The distinction mattered: a model that excels on SWE-bench Verified might be highly capable at resolving well-specified bugs in popular frameworks, but SWE-Bench Pro tested whether that capability extended to the messier, more ambiguous, more architecturally complex problems that senior engineers encounter daily.</p>
<p>Terminal-Bench, the second benchmark on which GPT-5.3-Codex set records, measured a fundamentally different dimension of coding capability: autonomous terminal operations <span class="citation" data-cites="openai2026_codex">(<a href="#ref-openai2026_codex" role="doc-biblioref">OpenAI 2026</a>)</span>. Where SWE-bench evaluated a model’s ability to produce a correct code patch, Terminal-Bench evaluated its ability to operate within a real computing environment — navigating file systems, executing build commands, interpreting system outputs, managing dependencies, and orchestrating multi-step workflows through the command line. Terminal-Bench was, in effect, a test of whether an AI system could do the operational work that software engineers perform around and between writing code: the debugging, the deployment, the environment management that constitute a significant fraction of an engineer’s day.</p>
<p>The fact that GPT-5.3-Codex achieved records on both benchmarks simultaneously was significant. It meant the model’s capabilities were not narrowly optimized for one kind of task. It could both write correct code and operate the surrounding infrastructure — a combination that no previous model had demonstrated at the same level of competence. This combination is precisely what real-world software engineering demands. A model that can write a perfect patch but cannot set up the test environment to verify it, or a model that can operate a terminal but cannot write the code to deploy, is of limited practical use. GPT-5.3-Codex closed that gap.</p>
<p>Taken together, the multi-benchmark evidence paints a picture of convergence: across multiple benchmarks, multiple organizations, and multiple evaluation methodologies, AI coding ability is improving rapidly and consistently. SWE-bench Verified, SWE-Bench Pro, Terminal-Bench, and the real-world productivity data from the <em>Science</em> study all point in the same direction. The breadth rules out flukes. The consistency rules out benchmark gaming. What remains is a replicable, accelerating trend in AI’s ability to perform the work that has defined the software engineering profession for fifty years.</p>
</section>
<section id="the-benchmarks-blind-spots" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="the-benchmarks-blind-spots"><span class="header-section-number">3.9</span> The Benchmark’s Blind Spots</h2>
<p>The 79.2% score is real. So are its limitations.</p>
<p>In October 2024, a team led by Reem Aleithan published SWE-Bench+, a systematic audit of the original dataset. Their findings were uncomfortable. In 32.67% of resolved instances, the solution had been directly provided in the issue report or its comments — what the authors called “solution leakage.” Another 31.08% of passed patches were flagged as suspicious due to weak test cases that couldn’t reliably verify correctness. When these problematic instances were filtered out, SWE-Agent’s resolution rate with GPT-4 dropped from 12.47% to 3.97%.</p>
<!-- PROOF: url=https://arxiv.org/abs/2410.06992v2 | accessed=2026-02-14 | key=aleithan2024_swebenchplus -->
<p>The contamination problem cuts deeper still. In June 2025, Shanchao Liang and colleagues published “The SWE-Bench Illusion,” demonstrating that frontier models could identify the correct buggy file path 76% of the time using <em>only</em> the issue description — no codebase access required. On repositories outside SWE-bench, that accuracy dropped to 53%. The models weren’t just reasoning about the code. They were remembering it.</p>
<!-- PROOF: url=https://arxiv.org/abs/2506.12286 | accessed=2026-02-14 | key=liang2025_swebench_illusion -->
<p>Then there’s the scope problem. An Epoch AI analysis found that 87% of SWE-bench Verified tasks are bug fixes. Only 9% involve feature requests. Django alone accounts for nearly half the dataset, and 39% of tasks were rated “trivial changes” requiring less than fifteen minutes for a human. The benchmark doesn’t test system architecture, API design, security review, or any of the higher-order work that separates a senior engineer from a junior one.</p>
<!-- PROOF: url=https://epoch.ai/blog/what-skills-does-swe-bench-verified-evaluate | accessed=2026-02-14 | key=epoch2025_swebench_skills -->
<p>None of this invalidates the trajectory. The improvement from 2.7% to 79.2% is genuine, and it measures something that matters — the ability to find your way through a codebase and produce a working fix. But the score doesn’t tell you whether the fix introduced a security vulnerability. It doesn’t measure whether the code is maintainable. And it can’t tell you whether the model could have designed the system it’s patching.</p>
<p>Two falsification conditions are worth watching. First: if SWE-bench scores above 80% fail to correlate with measurable productivity gains in real-world engineering teams by late 2026, the benchmark’s predictive value is weaker than assumed. Second: if models scoring 75%+ on SWE-bench Verified score below 40% on SWE-Bench Pro — the harder, longer-horizon variant — then the original benchmark measures a far narrower slice of engineering than its reputation suggests.</p>
</section>
<section id="what-79.2-means-for-ten-engineers" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="what-79.2-means-for-ten-engineers"><span class="header-section-number">3.10</span> What 79.2% Means for Ten Engineers</h2>
<p>Strip away the benchmark abstractions. What does a 79.2% SWE-bench score mean for a working software team?</p>
<p>Consider a team of ten engineers at a mid-size technology company. They maintain a production codebase — maybe two hundred thousand lines of Python, a REST API, a React frontend, the usual supporting infrastructure of databases, caches, and job queues. Bugs come in. Features get requested. The daily rhythm is triage, reproduce, trace, fix, test, submit. A typical engineer closes three to five bug-fix tickets per day, depending on complexity. The team, collectively, resolves somewhere between 30 and 50 issues daily.</p>
<p>Some are trivial: a missing import, a typo in a configuration value, a null pointer that should have been caught in review. Some are hard: a race condition that manifests only under load, a data corruption bug three layers deep in a dependency chain. Most fall in between.</p>
<p>SWE-bench Verified tasks sit in that middle range: real bugs in real codebases, with clear descriptions and existing test suites. At 79.2%, an AI system paired with an agentic framework can resolve roughly four out of five such tasks. Apply that rate to the team’s daily bug queue, and 24 to 40 of those issues could be drafted by AI — not perfectly, not without review, but with a first-pass solution that a senior engineer can evaluate in minutes rather than building from scratch.</p>
<p>Here’s what changes. The human engineers don’t vanish. They shift. Less time on the patch-and-test cycle. More time on what SWE-bench can’t measure: system design, code review of AI-generated patches, architectural decisions, performance optimization, the messy work of translating vague business requirements into precise technical specifications.</p>
<p>This isn’t hypothetical anymore. By early 2026, engineering teams using AI coding tools consistently reported that routine bug-fix time had dropped substantially — though the exact reduction varied by team, codebase, and tooling maturity. Hours spent on design, planning, and review held roughly constant. Total effort didn’t shrink. The composition changed. And the teams that adapted fastest were the ones with experienced engineers who could evaluate AI output quickly and catch the subtle errors — a pattern that mirrors the experience gap documented in <a href="#sec-experience-gap" class="quarto-xref"><span class="quarto-unresolved-ref">sec-experience-gap</span></a>.</p>
<p>The scorecard isn’t about replacement. It’s about reallocation. A 79.2% SWE-bench score doesn’t mean a team of ten becomes a team of two. It means a team of ten can attempt what previously required twenty — if they have the senior talent to direct the AI and the institutional willingness to reorganize around new capabilities. The benchmark measures the engine. The impact depends on who’s driving.</p>
<p>A newly hired software engineer in 2023 spent most of their first year on bug fixes, test writing, and code maintenance — the exact category where AI now scores 79.2%. By 2026, that work was increasingly routed through AI systems, reviewed rather than written by humans. Fewer reps at the keyboard. Fewer mistakes to learn from. Fewer late nights tracing through unfamiliar code. The profession was being reshaped from the bottom up — not by eliminating engineers, but by compressing the apprenticeship that had always created them.</p>
<p>The <em>Science</em> study’s 29% finding, the experience gap data, the benchmark’s blind spots, and the multi-benchmark convergence documented in this chapter collectively paint a picture that is more textured than either the optimists or the pessimists typically allow. AI is genuinely transforming software engineering. The transformation is measurable, replicable, and accelerating. But it is not uniform. It benefits the skilled more than the unskilled. It works better on well-specified tasks than on ambiguous ones. And it has reached a point where the most important question is no longer “how good is the AI at coding?” but “how does the AI’s coding ability interact with human organizations, career structures, and economic incentives?”</p>
<p>The benchmarks document the capability. The adoption data document the uptake. But the full impact — on jobs, on education, on the structure of the software industry — depends on forces that benchmarks cannot measure: management decisions, hiring policies, educational curricula, and the willingness of millions of individual engineers to adapt their workflow. The data presented in this chapter establishes that the technical preconditions for massive disruption are in place. Whether, when, and how that disruption manifests is the subject of later chapters.</p>
<p>For new entrants to the profession, the benchmark data posed a particular challenge. The traditional apprenticeship model — learn to code, get a junior position, spend years building experience through implementation work — assumed that implementation work would exist. If AI was already handling 79% of the bug-fixing, test-writing, and code-maintenance tasks that had always been assigned to junior developers, the question wasn’t just whether junior positions would exist. It was whether the path from junior to senior would survive. The skills that made senior engineers valuable — architectural judgment, system design, debugging intuition — were all built through years of hands-on implementation. Remove the implementation, and you removed the training ground. The benchmark revolution wasn’t just changing what software engineers did. It was potentially breaking the pipeline that created them.</p>
<p>The next chapter examines another trend that may prove even more consequential: the exponential growth in how long AI systems can work autonomously without human intervention. If SWE-bench measures how well AI can code, METR’s time horizon metric measures how long it can keep coding — and the implications of that metric are staggering.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Practitioner's Tool: Benchmark Assessment Tool">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practitioner’s Tool: Benchmark Assessment Tool
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a team evaluating whether AI coding tools are ready for their specific use case, the benchmarks tell part of the story. The rest depends on the nature of the work.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 43%">
<col style="width: 19%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Task Type</th>
<th>AI Capability (Feb 2026)</th>
<th>Readiness</th>
<th>Key Risk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bug fixes (well-specified)</td>
<td>Very high (79.2% SWE-bench)</td>
<td>Production-ready</td>
<td>Over-reliance on benchmark scope</td>
</tr>
<tr class="even">
<td>Test generation</td>
<td>High</td>
<td>Production-ready</td>
<td>Tests may mirror implementation errors</td>
</tr>
<tr class="odd">
<td>Code refactoring</td>
<td>High</td>
<td>Ready with review</td>
<td>Architectural judgment may be shallow</td>
</tr>
<tr class="even">
<td>New feature implementation</td>
<td>Medium-high</td>
<td>Ready with specification</td>
<td>Spec quality determines output quality</td>
</tr>
<tr class="odd">
<td>Architecture design</td>
<td>Medium</td>
<td>Augmentation only</td>
<td>Lacks cross-system context</td>
</tr>
<tr class="even">
<td>Security-critical code</td>
<td>Medium</td>
<td>Human review required</td>
<td>Adversarial edge cases underrepresented</td>
</tr>
<tr class="odd">
<td>Legacy system migration</td>
<td>Low-medium</td>
<td>Augmentation only</td>
<td>Insufficient context about undocumented behavior</td>
</tr>
</tbody>
</table>
<p>The honest reading: benchmarks measure what benchmarks measure. SWE-bench tests bug-fixing on open-source Python projects with well-defined test suites. Your codebase is probably not an open-source Python project with well-defined test suites. The 79.2% score is a ceiling for ideal conditions, not a floor for real-world deployment. The practical capability for your team will be lower — how much lower depends on how far your work diverges from the benchmark’s conditions.</p>
<p>The gap between benchmark performance and practical performance is itself a finding worth tracking. As models improve, that gap should narrow. If it doesn’t — if 90% SWE-bench scores still translate to 50% real-world success rates — the benchmarks were measuring the wrong thing all along. That possibility should be taken seriously. Benchmarks are mirrors, and mirrors show you what you designed them to show. SWE-bench was designed to measure bug-fixing capability on open-source Python projects. It measures that well. Whether it measures “software engineering ability” in any broader sense is an open question that the industry has been remarkably reluctant to ask.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Data Sources
</div>
</div>
<div class="callout-body-container callout-body">
<p>All SWE-bench scores cited in this chapter are drawn from the official SWE-bench leaderboard, Epoch AI’s benchmark tracker, and the releasing organizations’ official announcements. Scores are for SWE-bench Verified unless otherwise noted. Full data is available in <code>data/swe-bench.csv</code>.</p>
</div>
</div>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-anthropic2024_swebench" class="csl-entry" role="listitem">
Anthropic. 2024. <span>“<span>SWE</span>-Bench Sonnet.”</span> October. <a href="https://www.anthropic.com/research/swe-bench-sonnet">https://www.anthropic.com/research/swe-bench-sonnet</a>.
</div>
<div id="ref-cnbc2025_layoffs" class="csl-entry" role="listitem">
CNBC. 2025. <span>“White-Collar Layoffs, <span>AI</span>, Cost Cutting, Tariffs.”</span> CNBC, November. <a href="https://www.cnbc.com/2025/11/04/white-collar-layoffs-ai-cost-cutting-tariffs.html">https://www.cnbc.com/2025/11/04/white-collar-layoffs-ai-cost-cutting-tariffs.html</a>.
</div>
<div id="ref-cognition2024_devin" class="csl-entry" role="listitem">
Cognition Labs. 2024. <span>“Devin: <span>SWE</span>-Bench Technical Report.”</span> March. <a href="https://cognition.ai/blog/swe-bench-technical-report">https://cognition.ai/blog/swe-bench-technical-report</a>.
</div>
<div id="ref-daniotti2026_aicoding" class="csl-entry" role="listitem">
Daniotti, Simone et al. 2026. <span>“Who Is Using <span>AI</span> to Code? <span>Global</span> Diffusion and Impact of Generative <span>AI</span>.”</span> <em>Science</em>, January 22. <a href="https://www.science.org/doi/10.1126/science.adz9311">https://www.science.org/doi/10.1126/science.adz9311</a>.
</div>
<div id="ref-deepseek2024_v3" class="csl-entry" role="listitem">
DeepSeek-AI. 2024. <span>“<span>DeepSeek</span>-<span>V3</span> Technical Report.”</span> December. <a href="https://arxiv.org/abs/2412.19437">https://arxiv.org/abs/2412.19437</a>.
</div>
<div id="ref-deepseek2025_r1" class="csl-entry" role="listitem">
DeepSeek-AI. 2025. <span>“<span>DeepSeek</span>-<span>R1</span>: Incentivizing Reasoning Capability in <span>LLMs</span> via Reinforcement Learning.”</span> January 20. <a href="https://arxiv.org/abs/2501.12948">https://arxiv.org/abs/2501.12948</a>.
</div>
<div id="ref-epoch2025_swebench" class="csl-entry" role="listitem">
Epoch AI. 2025. <span>“<span>SWE</span>-Bench Verified Benchmark Tracker.”</span> <a href="https://epoch.ai/benchmarks/swe-bench-verified">https://epoch.ai/benchmarks/swe-bench-verified</a>.
</div>
<div id="ref-google2025_gemini3" class="csl-entry" role="listitem">
Google DeepMind. 2025. <span>“The <span>AI</span> Model Race Reaches Singularity Speed.”</span> Vertu, November. <a href="https://vertu.com/lifestyle/the-ai-model-race-reaches-singularity-speed/">https://vertu.com/lifestyle/the-ai-model-race-reaches-singularity-speed/</a>.
</div>
<div id="ref-hbr2026_aijobs" class="csl-entry" role="listitem">
Harvard Business Review. 2026. <span>“Companies Are Laying Off Workers Because of <span>AI</span>’s Potential, Not Its Performance.”</span> Harvard Business Review, January. <a href="https://hbr.org/2026/01/companies-are-laying-off-workers-because-of-ais-potential-not-its-performance">https://hbr.org/2026/01/companies-are-laying-off-workers-because-of-ais-potential-not-its-performance</a>.
</div>
<div id="ref-openai2023_gpt4" class="csl-entry" role="listitem">
OpenAI. 2023. <span>“<span>GPT</span>-4.”</span> March. <a href="https://openai.com/index/gpt-4-research/">https://openai.com/index/gpt-4-research/</a>.
</div>
<div id="ref-openai2024_swebenchverified" class="csl-entry" role="listitem">
OpenAI. 2024. <span>“Introducing <span>SWE</span>-Bench Verified.”</span> August. <a href="https://openai.com/index/introducing-swe-bench-verified/">https://openai.com/index/introducing-swe-bench-verified/</a>.
</div>
<div id="ref-openai2026_codex" class="csl-entry" role="listitem">
OpenAI. 2026. <span>“Introducing <span>GPT</span>-5.3-<span>Codex</span>.”</span> February 5. <a href="https://openai.com/index/introducing-gpt-5-3-codex/">https://openai.com/index/introducing-gpt-5-3-codex/</a>.
</div>
<div id="ref-pichai2025_bbc" class="csl-entry" role="listitem">
Pichai, Sundar. 2025. <span>“<span>Google CEO</span> Sundar Pichai on <span>AI</span>.”</span> BBC, January. <a href="https://www.bbc.com/news/articles/c0rz7d22lmpo">https://www.bbc.com/news/articles/c0rz7d22lmpo</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = true;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/02-voices-of-warning.html" class="pagination-link" aria-label="The Chorus of Warnings">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Chorus of Warnings</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/04-autonomous-frontier.html" class="pagination-link" aria-label="The Autonomous Frontier">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">The Autonomous Frontier</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "How SWE-bench Verified became the gold standard for measuring AI coding ability --- and how the scores went from laughable to alarming in less than two years."</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2026-02-12</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu"># The Benchmark Revolution {#sec-benchmark-revolution}</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>In the fall of 2023, Carlos Jiménez sat at a workstation in Princeton, New Jersey, watching another language model fail. Output scrolled across his terminal --- wrong file, wrong function, patch rejected by the test suite. The PhD candidate had grown up in Salt Lake City, studied computer science at the University of Utah, then headed east to work with professor Karthik Narasimhan on a problem that sounded simple and turned out to be brutally hard: could a language model fix real software bugs?</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- PROOF: url=https://www.carlosejimenez.com/ | accessed=2026-02-14 | key=jimenez_bio --&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- PROOF: url=https://arxiv.org/abs/2310.06770 | accessed=2026-02-14 | key=jimenez2024_swebench --&gt;</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>It was a moment of peak AI hype. ChatGPT had launched the previous November and reached a hundred million users in two months. Every tech company was bolting AI features onto its products. But Jiménez wasn't building chatbots. He wanted to know something specific: could these systems do the *work* --- the tedious, detail-oriented, test-it-till-it-passes work --- of professional software engineering?</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>He'd spent months building the answer machine. SWE-bench: 2,294 tasks scraped from twelve production Python repositories --- Django, Flask, scikit-learn, sympy, and others. Each task was a real bug report filed by a real developer, paired with the full codebase and a test suite that would judge whether the fix worked. No toy problems. No LeetCode puzzles. The actual daily grind of software maintenance.</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>The protocol was merciless. Give the model the bug report. Give it the codebase. No hints about which file to edit, no guidance on approach. Just: here's the problem, here's the code, fix it.</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>GPT-4 --- the most capable model available --- resolved 2.7% of the tasks. One in thirty-seven. Jiménez had designed the benchmark to be hard. He hadn't expected it to be *this* hard.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>He submitted the paper to ICLR, where it was accepted for the 2024 conference. He couldn't have known that within two years, every major AI lab on the planet would be racing to top his leaderboard --- that the score would climb from that initial 2.7% to 79.2% --- that the measuring stick he'd built at Princeton would become the most-cited number in arguments about whether artificial intelligence was coming for the software engineering profession.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>The voices of warning documented in the previous chapter made bold claims. But predictions are cheap. Evidence is what matters. And in the field of AI-assisted software engineering, Jiménez's benchmark became the definitive measure of whether those predictions were coming true.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## What SWE-bench Actually Measures</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>SWE-bench is not an artificial test. It does not ask models to solve textbook exercises or complete coding puzzles. Instead, it draws from real issues filed against real open-source repositories --- projects like Django, Flask, scikit-learn, and sympy. Each task consists of a bug report or feature request, the corresponding codebase, and the test suite that defines whether the fix is correct <span class="co">[</span><span class="ot">@epoch2025_swebench</span><span class="co">]</span>.</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>To solve a SWE-bench task, an AI system must:</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Read and understand the issue description</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Explore a large, unfamiliar codebase</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Identify the relevant files and functions</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Write a correct patch that resolves the issue</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Pass the existing test suite without breaking anything</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>The tasks demand the daily work of professional software engineers --- reading comprehension, code navigation, debugging intuition, and the ability to reason about complex system interactions.</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>In August 2024, OpenAI and the benchmark authors introduced SWE-bench Verified, a human-audited subset of 500 tasks designed to eliminate ambiguous or poorly specified issues <span class="co">[</span><span class="ot">@openai2024_swebenchverified</span><span class="co">]</span>. This version became the standard against which all subsequent models have been measured.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>The need for a verified subset was itself revealing. The original SWE-bench dataset contained tasks where the "correct" solution was disputed, where the test suite was incomplete, or where the issue description was too vague for even a skilled human to resolve reliably. By hand-auditing 500 tasks, the benchmark authors created a cleaner signal --- one that separated genuine AI capability from noise. The trade-off was a smaller dataset, but the gains in measurement reliability were substantial. After August 2024, virtually every major lab reported results on Verified rather than the original benchmark, making it the de facto standard for the field.</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Progression: From 2.7% to 79.2%</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>The trajectory of SWE-bench scores reads like an exponential curve. @fig-swe-bench-timeline shows the progression from early 2024 through February 2026.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="al">![SWE-bench Verified progression: AI coding performance from January 2024 through February 2026.](../images/generated/swe-bench-timeline.png)</span>{#fig-swe-bench-timeline}</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>The key milestones, summarized in @tbl-swebench-scores, tell their own story:</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>| Date | Model | Score | Organization |</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>|:-----|:------|------:|:-------------|</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>| Jan 2024 | GPT-4 (RAG baseline) | 2.7% | OpenAI |</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>| Mar 2024 | Devin | 13.86% | Cognition |</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>| Apr 2024 | AutoCodeRover | 22.0% | NUS/Industry |</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>| Jun 2024 | MentatBot + GPT-4o | 38.0% | AbanteAI |</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>| Jul 2024 | CodeStory Aide | 43.0% | CodeStory |</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>| Aug 2024 | GPT-4o (Verified baseline) | 33.0% | OpenAI |</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>| Sep 2024 | o1-preview | 45.0% | OpenAI |</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>| Oct 2024 | Claude 3.5 Sonnet | 49.0% | Anthropic |</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>| Dec 2024 | o3 | 72.0% | OpenAI |</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>| Feb 2025 | Claude 3.7 Sonnet | 55.0% | Anthropic |</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>| May 2025 | Claude Sonnet 4 | 62.0% | Anthropic |</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>| Jun 2025 | TRAE (multi-model) | 75.2% | ByteDance |</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>| Aug 2025 | GPT-5 | 74.9% | OpenAI |</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>| Nov 2025 | Gemini 3 Pro + agent | 77.4% | Google DeepMind |</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>| Nov 2025 | Claude Opus 4.5 + agent | 79.2% | Anthropic |</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>| Dec 2025 | GPT-5.2 | 75.4% | OpenAI |</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>| Feb 2026 | Claude Opus 4.6 (Thinking) | 79.2% | Anthropic |</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>: Top SWE-bench Verified scores by date, showing the progression from single-digit to near-80% performance. {#tbl-swebench-scores}</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>Several patterns emerge from this data.</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Early Phase: Proof of Concept (Jan--Jun 2024)</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>When GPT-4 scored 2.7% with a simple retrieval-augmented generation approach in January 2024, many researchers viewed AI-assisted software engineering as an interesting but impractical research direction. The score meant the model could solve roughly one in forty real-world bugs --- not a useful tool for any professional.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>Devin's March 2024 announcement at 13.86% was significant not for its absolute score but for what it represented. Cognition Labs marketed Devin as "the first AI software engineer," and while the marketing outpaced the reality, the five-fold improvement over the RAG baseline in just two months signaled that the problem was tractable <span class="co">[</span><span class="ot">@cognition2024_devin</span><span class="co">]</span>.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>By mid-2024, multi-model approaches combining Claude 3.5 Sonnet and GPT-4o were pushing past 40%. The benchmark was no longer a curiosity. It was a competitive arena.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Breakthrough Phase: Reasoning Models (Sep 2024--Feb 2025)</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>The introduction of reasoning models --- OpenAI's o1 in September 2024 and o3 in December 2024 --- represented a qualitative shift. These models did not simply generate code faster; they thought about problems differently, using chain-of-thought reasoning to plan their approach before writing a single line.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>o1-preview scored 45%, respectable but not groundbreaking. o3, released in December 2024, scored 72% --- a 27-percentage-point jump in three months <span class="co">[</span><span class="ot">@openai2023_gpt4</span><span class="co">]</span>. This single leap was larger than the entire improvement from January through September 2024.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>Meanwhile, Anthropic's Claude 3.5 Sonnet had reached 49% in October, and Claude 3.7 Sonnet would reach 55% by February 2025 --- steady, substantial gains from a different architectural approach <span class="co">[</span><span class="ot">@anthropic2024_swebench</span><span class="co">]</span>.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Maturity Phase: Converging at the Top (Mar 2025--Feb 2026)</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>By mid-2025, the leading models were converging. Claude Sonnet 4 hit 62%. ByteDance's TRAE reached 75.2% using a multi-model approach. GPT-5 landed at 74.9%. The differences between top models were narrowing even as absolute performance climbed.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="fu">### The November 2025 Cluster: The Inflection Point {#sec-november-cluster}</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>November 2025 stands as the most consequential month in the history of AI coding benchmarks. Within a span of six days, two models shattered what had seemed like a ceiling, and in doing so redefined the practical meaning of artificial intelligence for the software engineering profession.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>On November 18, Google DeepMind released Gemini 3 Pro, which scored 77.4% on SWE-bench Verified when paired with an agentic scaffolding <span class="co">[</span><span class="ot">@epoch2025_swebench; @google2025_gemini3</span><span class="co">]</span>. The score represented a 2.5-percentage-point improvement over GPT-5's August 2025 result of 74.9% --- a modest gain in absolute terms, but one that carried it past the 75% threshold. At 77.4%, the model was resolving more than three out of every four verified software engineering tasks. For the first time, the balance had tipped: there were more tasks the AI could solve than tasks it could not.</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>Six days later, on November 24, Anthropic released Claude Opus 4.5. Its SWE-bench Verified score of 79.2% did not merely exceed Gemini 3 Pro's result. It established a new ceiling that has yet to be surpassed as of this writing <span class="co">[</span><span class="ot">@epoch2025_swebench</span><span class="co">]</span>. The 1.8-percentage-point gap between Gemini 3 Pro and Opus 4.5 may appear narrow, but at the top of a saturating benchmark, each additional point represents the resolution of progressively harder problems --- the ambiguous bug reports, the deeply nested codebases, the issues that require not just technical skill but something approaching engineering judgment.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>What made the November cluster significant was the concentration. Two models from two competing organizations, released within a week of each other, both pushing past 77%. Because the underlying capabilities --- chain-of-thought reasoning, tool use during problem-solving, sustained error recovery --- had matured independently, near-80% performance was now reproducible across different architectures and different training approaches. Convergence, not coincidence.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>The scores also need to be understood in the context of the broader November model release wave discussed in @sec-november-precedent. Grok 4.1 had arrived on November 17, pushing LMArena Elo to 1,483. Gemini 3 topped that the next day at 1,501 Elo. Opus 4.5 arrived six days later with the SWE-bench crown. And within three weeks, GPT-5.2 and Gemini 3 Deep Think would further extend the frontier of reasoning capability. The competitive pressure was intense and mutually reinforcing. Each release gave the other labs' customers a reason to demand better tools, and each lab had models ready or nearly ready that could deliver.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>By February 2026, when Claude Opus 4.6 matched the 79.2% with its thinking capabilities, the benchmark had arguably reached a saturation point. The remaining 20% of unsolved tasks likely represented genuinely ambiguous issues, tasks requiring deep domain knowledge, or problems that were poorly specified in the original repositories. AI competence on standard software engineering tasks was settled. What remained was the meaning of the ceiling --- whether the last 20% represented a fundamental limit or merely the next target.</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="fu">## What 79% Means for Software Engineering</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>Sundar Pichai had called it "the most profound technology humanity is ever working on" <span class="co">[</span><span class="ot">@pichai2025_bbc</span><span class="co">]</span>. A score of 79.2% on SWE-bench Verified gave that claim specific, concrete implications for the software engineering profession.</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- PROOF: url=https://fortune.com/2025/12/02/ai-wipes-jobs-google-ceo-sundar-pichai-everyday-people-to-adapt-accordingly/ | accessed=2026-02-14 | key=pichai2025_bbc --&gt;</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>It means that when presented with a random bug report from a production open-source codebase, an AI system can trace through the code, identify the problem, and write a correct fix roughly four times out of five. It can do this in minutes rather than the hours or days a human engineer might require. It can do it at any time of day, without needing to ramp up on the codebase, and without introducing the human errors that come from fatigue or distraction.</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning}</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="fu">## What 79% Does Not Mean</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>A 79.2% SWE-bench score does not mean AI can replace 79.2% of software engineers. Software engineering encompasses far more than resolving bug reports: architecture design, requirements gathering, code review, system operations, stakeholder communication, and judgment calls about trade-offs. SWE-bench measures one important dimension of the job, but not the whole job.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>That said, resolving issues against existing codebases is a significant fraction of what junior and mid-level engineers spend their time on. The implications for entry-level software engineering roles are real and immediate.</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>The implications for hiring are already visible. By late 2025, multiple technology companies had begun restructuring their engineering organizations, reducing headcount at the junior level while increasing investment in senior engineers who could supervise and direct AI systems <span class="co">[</span><span class="ot">@cnbc2025_layoffs</span><span class="co">]</span>. The traditional career pipeline --- where graduates enter as junior engineers, fix bugs, write tests, and gradually take on more complex work --- is being compressed. If an AI can handle the bug-fixing and test-writing that once served as the training ground for new engineers, then the on-ramp to the profession narrows. Companies that once posted dozens of entry-level software engineering positions began, by early 2026, posting fewer such roles and instead seeking candidates with the ability to architect systems, review AI-generated code, and specify complex requirements clearly <span class="co">[</span><span class="ot">@hbr2026_aijobs</span><span class="co">]</span>.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>The economic implications extend beyond hiring. If an AI system can resolve most routine software engineering tasks, then organizations need fewer humans for those tasks. This does not necessarily mean fewer software engineers in total --- demand for software is effectively infinite, and AI may enable small teams to tackle projects that previously required large ones. But it does mean that the nature of the work is changing, and that the skills that defined a good junior engineer in 2023 are not the same skills that will define one in 2027.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="fu">## The 29% Finding {#sec-29-percent}</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>SWE-bench measures what AI can do in a controlled evaluation setting. But how much code is AI actually writing in the real world? On January 22, 2026, a study published in *Science* --- one of the most prestigious peer-reviewed journals in the world --- provided the first rigorous answer. The number was startling: 29% of Python functions committed to GitHub by U.S.-based developers were AI-generated <span class="co">[</span><span class="ot">@daniotti2026_aicoding</span><span class="co">]</span>.</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>The study, led by Simone Daniotti at the Complexity Science Hub and Utrecht University, was notable for the rigor of its methodology. Rather than relying on self-reported surveys --- which are prone to social desirability bias and imprecise definitions of what counts as "AI-generated" --- the team trained a neural classifier to detect AI-generated Python functions directly from code. They applied this classifier to more than 30 million GitHub commits from approximately 160,000 developers, creating what was by far the largest empirical study of AI code adoption ever conducted <span class="co">[</span><span class="ot">@daniotti2026_aicoding</span><span class="co">]</span>.</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>The 29% figure represented a dramatic acceleration. The study tracked adoption over time and found that the share of AI-generated Python functions among U.S. developers had risen from approximately 5% in 2022 to 29% by late 2024 and early 2025 --- a nearly sixfold increase in roughly two years. Given the rate of capability improvement documented elsewhere in this chapter, the figure was almost certainly higher by the time the study was published in January 2026.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>International comparisons revealed significant geographic variation. France stood at 24%, Germany at 23%, India at 20%, Russia at 15%, and China at 12% <span class="co">[</span><span class="ot">@daniotti2026_aicoding</span><span class="co">]</span>. The U.S. led by a substantial margin, reflecting earlier access to frontier AI coding tools, higher adoption of tools like GitHub Copilot and Claude Code, and a developer culture that was more receptive to AI-assisted workflows. The gap between the U.S. and China was particularly striking --- a factor of nearly 2.5 --- and raised questions about whether AI coding adoption would become a source of competitive advantage between technology ecosystems.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>The economic impact was substantial. The study estimated that AI-generated code contributed $23 to $38 billion in annual economic value to U.S. programming tasks, calculated from the overall 3.6% increase in quarterly output (measured in online code contributions) observed across their sample <span class="co">[</span><span class="ot">@daniotti2026_aicoding</span><span class="co">]</span>. This figure was conservative by design, capturing only the directly measurable productivity effect and excluding harder-to-quantify benefits like reduced time-to-market, lower defect rates, or the enablement of projects that would not have been attempted without AI assistance.</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Experience Gap {#sec-experience-gap}</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>The *Science* study's most consequential finding went beyond adoption rates or economic value. It revealed who benefited from AI coding tools --- and who didn't.</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>Less experienced programmers used AI in 37% of their code --- a higher adoption rate than any other group. They were the most enthusiastic adopters, the most willing to delegate to AI tools, and the most likely to incorporate AI-generated functions into their commits. But their productivity gains were statistically indistinguishable from zero <span class="co">[</span><span class="ot">@daniotti2026_aicoding</span><span class="co">]</span>.</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Experienced developers, by contrast, used AI in 27% of their code --- a lower adoption rate --- but saw a 6.2% increase in commit rates at that level of adoption. The gap mattered. Six percent was the difference between a tool that made you more productive and one that merely rearranged how you spent your time <span class="co">[</span><span class="ot">@daniotti2026_aicoding</span><span class="co">]</span>.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>The finding was deeply counterintuitive and deeply consequential. The conventional wisdom about AI coding tools was that they would be the great equalizer --- that by automating the routine aspects of programming, they would allow less experienced developers to punch above their weight, closing the gap between junior and senior engineers. The *Science* study found the opposite. The technology widens rather than narrows skill-based disparities in the profession.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>The likely explanation involves the difference between generating code and evaluating code. AI coding tools excel at producing syntactically correct, functionally plausible code from a natural-language prompt. But knowing whether that code is correct --- whether it handles edge cases, whether it introduces security vulnerabilities, whether it integrates properly with the broader system, whether it makes the right architectural trade-offs --- requires exactly the kind of deep experience that junior developers lack. An experienced developer can review AI-generated code and quickly spot the subtle errors: the race condition, the missing null check, the inefficient database query that will scale poorly. A less experienced developer may accept the code at face value, spending their time generating more AI-written functions rather than ensuring the quality of each one.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>This finding reframes the debate about AI's impact on the software engineering labor market. If AI tools primarily benefit experienced developers --- making the already-productive more productive while leaving the less-experienced treading water --- then the implications for career development are troubling. The traditional apprenticeship model, where junior developers build expertise by writing code, making mistakes, and learning from the correction process, may be disrupted by a technology that allows juniors to bypass the learning phase entirely. They write less code, review less code, and debug less code --- the very activities through which expertise is built.</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>The parallel to other domains is instructive. When calculators became ubiquitous in mathematics education, teachers debated whether students still needed to learn long division. The consensus, eventually, was that understanding the underlying process mattered even if the tool could do it faster. Programming may face an analogous question: does it matter that a developer understands how to write a function if the AI writes it better? The *Science* study suggests the answer is yes --- because the developers who understand the underlying process are the ones who benefit from the tool, while those who do not understand it gain nothing.</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Acceleration Pattern</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>Perhaps the most important feature of the SWE-bench trajectory is not the absolute numbers but the rate of change. Consider the time required to achieve successive milestones:</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**2.7% to 13.9%**: ~2 months (January to March 2024)</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**13.9% to 49%**: ~7 months (March to October 2024)</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**49% to 72%**: ~2 months (October to December 2024)</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**72% to 79.2%**: ~11 months (December 2024 to November 2025)</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>The pattern shows a rapid acceleration through mid-range scores, followed by a slowdown as performance approaches the ceiling. This is characteristic of benchmark saturation: the easiest tasks are solved first, and each additional percentage point requires solving harder problems.</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>But this interpretation cuts both ways. The slowdown at the top may reflect genuine difficulty, or it may reflect the fact that 2025 saw fewer paradigm-shifting architectural innovations than 2024. The introduction of agent frameworks, extended thinking, and tool use during reasoning --- all of which appeared in 2025 --- may produce another acceleration phase.</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Competition Factor</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>One underappreciated driver of SWE-bench improvement is competition. By mid-2025, at least four major organizations were directly competing for the top score: Anthropic (Claude), OpenAI (GPT/o-series), Google DeepMind (Gemini), and a growing field of smaller players using multi-model approaches.</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>This competition created a flywheel. Each new high score generated headlines, attracted talent, and justified further investment. Anthropic's Claude 3.5 Sonnet hitting 49% in October 2024 prompted OpenAI to push o3 to 72% just two months later. That result, in turn, drove Anthropic to invest heavily in the agentic capabilities that would eventually produce the 79.2% score.</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>The presence of open-source competitors added another dimension entirely. In January 2025, DeepSeek released R1, an open-source reasoning model under an MIT license that scored 45% on SWE-bench Verified --- matching o1-preview's September 2024 result <span class="co">[</span><span class="ot">@deepseek2025_r1</span><span class="co">]</span>. DeepSeek-R1 was built atop the DeepSeek-V3 architecture, a 671-billion-parameter mixture-of-experts model that had been trained for a reported $6 million --- a fraction of the hundreds of millions that frontier labs were spending on comparable training runs <span class="co">[</span><span class="ot">@deepseek2024_v3</span><span class="co">]</span>. The consequences hit immediately. If an open-source model, trainable by a modestly funded Chinese lab, could match scores that OpenAI's proprietary reasoning system had achieved just four months earlier, then the competitive moat around frontier AI capabilities was thinner than anyone had assumed. The release sent shockwaves through the industry, contributing to an 18% single-day drop in NVIDIA's stock price and briefly making the DeepSeek chatbot the number-one app on Apple's iOS store <span class="co">[</span><span class="ot">@deepseek2025_r1</span><span class="co">]</span>. For SWE-bench specifically, the message was clear: the benchmark's middle range was no longer the exclusive domain of billion-dollar research budgets.</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="fu">## Beyond SWE-bench {#sec-beyond-swebench}</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>SWE-bench Verified is the most prominent coding benchmark, but it is not the only one, and the proliferation of alternative benchmarks tells its own story about the field's maturation.</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>SWE-Bench Pro emerged as a response to the saturation problem. As top models converged near 80% on SWE-bench Verified, the benchmark's ability to discriminate between frontier systems diminished. SWE-Bench Pro addressed this by selecting harder tasks --- issues that required deeper domain understanding, more complex multi-file modifications, and more sophisticated testing strategies. When GPT-5.3-Codex was released on February 5, 2026, OpenAI highlighted its new record on SWE-Bench Pro as evidence that the model's capabilities extended beyond the original benchmark's ceiling <span class="co">[</span><span class="ot">@openai2026_codex</span><span class="co">]</span>. The distinction mattered: a model that excels on SWE-bench Verified might be highly capable at resolving well-specified bugs in popular frameworks, but SWE-Bench Pro tested whether that capability extended to the messier, more ambiguous, more architecturally complex problems that senior engineers encounter daily.</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>Terminal-Bench, the second benchmark on which GPT-5.3-Codex set records, measured a fundamentally different dimension of coding capability: autonomous terminal operations <span class="co">[</span><span class="ot">@openai2026_codex</span><span class="co">]</span>. Where SWE-bench evaluated a model's ability to produce a correct code patch, Terminal-Bench evaluated its ability to operate within a real computing environment --- navigating file systems, executing build commands, interpreting system outputs, managing dependencies, and orchestrating multi-step workflows through the command line. Terminal-Bench was, in effect, a test of whether an AI system could do the operational work that software engineers perform around and between writing code: the debugging, the deployment, the environment management that constitute a significant fraction of an engineer's day.</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>The fact that GPT-5.3-Codex achieved records on both benchmarks simultaneously was significant. It meant the model's capabilities were not narrowly optimized for one kind of task. It could both write correct code and operate the surrounding infrastructure --- a combination that no previous model had demonstrated at the same level of competence. This combination is precisely what real-world software engineering demands. A model that can write a perfect patch but cannot set up the test environment to verify it, or a model that can operate a terminal but cannot write the code to deploy, is of limited practical use. GPT-5.3-Codex closed that gap.</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>Taken together, the multi-benchmark evidence paints a picture of convergence: across multiple benchmarks, multiple organizations, and multiple evaluation methodologies, AI coding ability is improving rapidly and consistently. SWE-bench Verified, SWE-Bench Pro, Terminal-Bench, and the real-world productivity data from the *Science* study all point in the same direction. The breadth rules out flukes. The consistency rules out benchmark gaming. What remains is a replicable, accelerating trend in AI's ability to perform the work that has defined the software engineering profession for fifty years.</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Benchmark's Blind Spots</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>The 79.2% score is real. So are its limitations.</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>In October 2024, a team led by Reem Aleithan published SWE-Bench+, a systematic audit of the original dataset. Their findings were uncomfortable. In 32.67% of resolved instances, the solution had been directly provided in the issue report or its comments --- what the authors called "solution leakage." Another 31.08% of passed patches were flagged as suspicious due to weak test cases that couldn't reliably verify correctness. When these problematic instances were filtered out, SWE-Agent's resolution rate with GPT-4 dropped from 12.47% to 3.97%.</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- PROOF: url=https://arxiv.org/abs/2410.06992v2 | accessed=2026-02-14 | key=aleithan2024_swebenchplus --&gt;</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>The contamination problem cuts deeper still. In June 2025, Shanchao Liang and colleagues published "The SWE-Bench Illusion," demonstrating that frontier models could identify the correct buggy file path 76% of the time using *only* the issue description --- no codebase access required. On repositories outside SWE-bench, that accuracy dropped to 53%. The models weren't just reasoning about the code. They were remembering it.</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- PROOF: url=https://arxiv.org/abs/2506.12286 | accessed=2026-02-14 | key=liang2025_swebench_illusion --&gt;</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>Then there's the scope problem. An Epoch AI analysis found that 87% of SWE-bench Verified tasks are bug fixes. Only 9% involve feature requests. Django alone accounts for nearly half the dataset, and 39% of tasks were rated "trivial changes" requiring less than fifteen minutes for a human. The benchmark doesn't test system architecture, API design, security review, or any of the higher-order work that separates a senior engineer from a junior one.</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- PROOF: url=https://epoch.ai/blog/what-skills-does-swe-bench-verified-evaluate | accessed=2026-02-14 | key=epoch2025_swebench_skills --&gt;</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>None of this invalidates the trajectory. The improvement from 2.7% to 79.2% is genuine, and it measures something that matters --- the ability to find your way through a codebase and produce a working fix. But the score doesn't tell you whether the fix introduced a security vulnerability. It doesn't measure whether the code is maintainable. And it can't tell you whether the model could have designed the system it's patching.</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>Two falsification conditions are worth watching. First: if SWE-bench scores above 80% fail to correlate with measurable productivity gains in real-world engineering teams by late 2026, the benchmark's predictive value is weaker than assumed. Second: if models scoring 75%+ on SWE-bench Verified score below 40% on SWE-Bench Pro --- the harder, longer-horizon variant --- then the original benchmark measures a far narrower slice of engineering than its reputation suggests.</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="fu">## What 79.2% Means for Ten Engineers</span></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>Strip away the benchmark abstractions. What does a 79.2% SWE-bench score mean for a working software team?</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>Consider a team of ten engineers at a mid-size technology company. They maintain a production codebase --- maybe two hundred thousand lines of Python, a REST API, a React frontend, the usual supporting infrastructure of databases, caches, and job queues. Bugs come in. Features get requested. The daily rhythm is triage, reproduce, trace, fix, test, submit. A typical engineer closes three to five bug-fix tickets per day, depending on complexity. The team, collectively, resolves somewhere between 30 and 50 issues daily.</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>Some are trivial: a missing import, a typo in a configuration value, a null pointer that should have been caught in review. Some are hard: a race condition that manifests only under load, a data corruption bug three layers deep in a dependency chain. Most fall in between.</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>SWE-bench Verified tasks sit in that middle range: real bugs in real codebases, with clear descriptions and existing test suites. At 79.2%, an AI system paired with an agentic framework can resolve roughly four out of five such tasks. Apply that rate to the team's daily bug queue, and 24 to 40 of those issues could be drafted by AI --- not perfectly, not without review, but with a first-pass solution that a senior engineer can evaluate in minutes rather than building from scratch.</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>Here's what changes. The human engineers don't vanish. They shift. Less time on the patch-and-test cycle. More time on what SWE-bench can't measure: system design, code review of AI-generated patches, architectural decisions, performance optimization, the messy work of translating vague business requirements into precise technical specifications.</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>This isn't hypothetical anymore. By early 2026, engineering teams using AI coding tools consistently reported that routine bug-fix time had dropped substantially --- though the exact reduction varied by team, codebase, and tooling maturity. Hours spent on design, planning, and review held roughly constant. Total effort didn't shrink. The composition changed. And the teams that adapted fastest were the ones with experienced engineers who could evaluate AI output quickly and catch the subtle errors --- a pattern that mirrors the experience gap documented in @sec-experience-gap.</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>The scorecard isn't about replacement. It's about reallocation. A 79.2% SWE-bench score doesn't mean a team of ten becomes a team of two. It means a team of ten can attempt what previously required twenty --- if they have the senior talent to direct the AI and the institutional willingness to reorganize around new capabilities. The benchmark measures the engine. The impact depends on who's driving.</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>A newly hired software engineer in 2023 spent most of their first year on bug fixes, test writing, and code maintenance --- the exact category where AI now scores 79.2%. By 2026, that work was increasingly routed through AI systems, reviewed rather than written by humans. Fewer reps at the keyboard. Fewer mistakes to learn from. Fewer late nights tracing through unfamiliar code. The profession was being reshaped from the bottom up --- not by eliminating engineers, but by compressing the apprenticeship that had always created them.</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>The *Science* study's 29% finding, the experience gap data, the benchmark's blind spots, and the multi-benchmark convergence documented in this chapter collectively paint a picture that is more textured than either the optimists or the pessimists typically allow. AI is genuinely transforming software engineering. The transformation is measurable, replicable, and accelerating. But it is not uniform. It benefits the skilled more than the unskilled. It works better on well-specified tasks than on ambiguous ones. And it has reached a point where the most important question is no longer "how good is the AI at coding?" but "how does the AI's coding ability interact with human organizations, career structures, and economic incentives?"</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>The benchmarks document the capability. The adoption data document the uptake. But the full impact --- on jobs, on education, on the structure of the software industry --- depends on forces that benchmarks cannot measure: management decisions, hiring policies, educational curricula, and the willingness of millions of individual engineers to adapt their workflow. The data presented in this chapter establishes that the technical preconditions for massive disruption are in place. Whether, when, and how that disruption manifests is the subject of later chapters.</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>For new entrants to the profession, the benchmark data posed a particular challenge. The traditional apprenticeship model --- learn to code, get a junior position, spend years building experience through implementation work --- assumed that implementation work would exist. If AI was already handling 79% of the bug-fixing, test-writing, and code-maintenance tasks that had always been assigned to junior developers, the question wasn't just whether junior positions would exist. It was whether the path from junior to senior would survive. The skills that made senior engineers valuable --- architectural judgment, system design, debugging intuition --- were all built through years of hands-on implementation. Remove the implementation, and you removed the training ground. The benchmark revolution wasn't just changing what software engineers did. It was potentially breaking the pipeline that created them.</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>The next chapter examines another trend that may prove even more consequential: the exponential growth in how long AI systems can work autonomously without human intervention. If SWE-bench measures how well AI can code, METR's time horizon metric measures how long it can keep coding --- and the implications of that metric are staggering.</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Practitioner's Tool: Benchmark Assessment Tool" icon=false}</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>For a team evaluating whether AI coding tools are ready for their specific use case, the benchmarks tell part of the story. The rest depends on the nature of the work.</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>| Task Type | AI Capability (Feb 2026) | Readiness | Key Risk |</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>|-----------|-------------------------|-----------|----------|</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>| Bug fixes (well-specified) | Very high (79.2% SWE-bench) | Production-ready | Over-reliance on benchmark scope |</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>| Test generation | High | Production-ready | Tests may mirror implementation errors |</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>| Code refactoring | High | Ready with review | Architectural judgment may be shallow |</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>| New feature implementation | Medium-high | Ready with specification | Spec quality determines output quality |</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>| Architecture design | Medium | Augmentation only | Lacks cross-system context |</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>| Security-critical code | Medium | Human review required | Adversarial edge cases underrepresented |</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>| Legacy system migration | Low-medium | Augmentation only | Insufficient context about undocumented behavior |</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>The honest reading: benchmarks measure what benchmarks measure. SWE-bench tests bug-fixing on open-source Python projects with well-defined test suites. Your codebase is probably not an open-source Python project with well-defined test suites. The 79.2% score is a ceiling for ideal conditions, not a floor for real-world deployment. The practical capability for your team will be lower --- how much lower depends on how far your work diverges from the benchmark's conditions.</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>The gap between benchmark performance and practical performance is itself a finding worth tracking. As models improve, that gap should narrow. If it doesn't --- if 90% SWE-bench scores still translate to 50% real-world success rates --- the benchmarks were measuring the wrong thing all along. That possibility should be taken seriously. Benchmarks are mirrors, and mirrors show you what you designed them to show. SWE-bench was designed to measure bug-fixing capability on open-source Python projects. It measures that well. Whether it measures "software engineering ability" in any broader sense is an open question that the industry has been remarkably reluctant to ask.</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Sources</span></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>All SWE-bench scores cited in this chapter are drawn from the official SWE-bench leaderboard, Epoch AI's benchmark tracker, and the releasing organizations' official announcements. Scores are for SWE-bench Verified unless otherwise noted. Full data is available in <span class="in">`data/swe-bench.csv`</span>.</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>:::</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/zeroshotpress/Something-Big-Already-Happened/edit/main/chapters/03-benchmark-revolution.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/zeroshotpress/Something-Big-Already-Happened/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>